GiCungBan/src/java/model/Demand.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package model;

/**
 *
 * @author PC
 */
public class Demand {
    private int Id;    
    private int UserID;
    private String Name;
    private double Amount;

    public Demand() {
    }

    public Demand(int UserID, String Name, double Amount) {
        this.UserID = UserID;
        this.Name = Name;
        this.Amount = Amount;
    }

    public Demand(int Id, int UserID, String Name, double Amount) {
        this.Id = Id;
        this.UserID = UserID;
        this.Name = Name;
        this.Amount = Amount;
    }
    
    
        

    public Demand(String Name, double Amount) {
        this.Name = Name;
        this.Amount = Amount;
    }

    public int getId() {
        return Id;
    }

    public void setId(int Id) {
        this.Id = Id;
    }

    public int getUserID() {
        return UserID;
    }

    public void setUserID(int UserID) {
        this.UserID = UserID;
    }
    
    

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public double getAmount() {
        return Amount;
    }

    public void setAmount(double Amount) {
        this.Amount = Amount;
    }

    @Override
    public String toString() {
        return "Demand{" + "Id=" + Id + ", UserID=" + UserID + ", Name=" + Name + ", Amount=" + Amount + '}';
    }
    

      
    
}

GiCungBan/src/java/model/Product.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package model;

import dal.OrderDetailDAO;
import java.sql.Timestamp;

/**
 *
 * @author ACER
 */
public class Product {

    private int id;
    private String name;
    private String description;
    private double price;
    private int sellerID;
    private String contactMethod;
    private String username;
    private String hiddenContent;
    private Timestamp createdAt;
    private Timestamp lastUpdated;
    private byte[] image;
    private String base64Image;
    private byte[] imageBytes;
  

    
    public Product() {
    }

    //Hien thi san pham trong home
    public Product(int id, String name, String description, double price, int sellerID, String contactMethod, String username, Timestamp createdAt, Timestamp lastUpdated) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.price = price;
        this.sellerID = sellerID;
        this.contactMethod = contactMethod;
        this.username = username;
        this.createdAt = createdAt;
        this.lastUpdated = lastUpdated;
    }

    // Them san pham
    public Product(String name, String description, double price, int sellerID, String contactMethod, String hiddenContent, Timestamp createdAt, Timestamp lastUpdated, byte[] image) {
        this.name = name;
        this.description = description;
        this.price = price;
        this.sellerID = sellerID;
        this.contactMethod = contactMethod;
        this.hiddenContent = hiddenContent;
        this.createdAt = createdAt;
        this.lastUpdated = lastUpdated;
        this.image = image;
    }

    //Update san pham
    public Product(int id, String name, String description, double price, String contactMethod, String hiddenContent, Timestamp lastUpdated, byte[] image) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.price = price;
        this.contactMethod = contactMethod;
        this.hiddenContent = hiddenContent;
        this.lastUpdated = lastUpdated;
        this.image = image;
    }

    public Product(int id, String name, String description, double price, int sellerID, String contactMethod, String username, String hiddenContent, Timestamp createdAt, Timestamp lastUpdated) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.price = price;
        this.sellerID = sellerID;
        this.contactMethod = contactMethod;
        this.username = username;
        this.hiddenContent = hiddenContent;
        this.createdAt = createdAt;
        this.lastUpdated = lastUpdated;
    }

    
    // get Product by Id -- Details sản phẩm
    public Product(int id, String name, String description, double price, int sellerID, String contactMethod, String username, Timestamp createdAt, Timestamp lastUpdated, byte[] image) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.price = price;
        this.sellerID = sellerID;
        this.contactMethod = contactMethod;
        this.username = username;
        this.createdAt = createdAt;
        this.lastUpdated = lastUpdated;
        this.image = image;
    }
    
    

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public int getSellerID() {
        return sellerID;
    }

    public void setSellerID(int sellerID) {
        this.sellerID = sellerID;
    }

    public String getContactMethod() {
        return contactMethod;
    }

    public void setContactMethod(String contactMethod) {
        this.contactMethod = contactMethod;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Timestamp getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getLastUpdated() {
        return lastUpdated;
    }

    public void setLastUpdated(Timestamp lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    public String getHiddenContent() {
        return hiddenContent;
    }

    public void setHiddenContent(String hiddenContent) {
        this.hiddenContent = hiddenContent;
    }

    public byte[] getImage() {
        return image;
    }

    public void setImage(byte[] image) {
        this.image = image;
    }

    public String getBase64Image() {
        return base64Image;
    }

    public void setBase64Image(String base64Image) {
        this.base64Image = base64Image;
    }

    public byte[] getImageBytes() {
        return imageBytes;
    }

    public void setImageBytes(byte[] imageBytes) {
        this.imageBytes = imageBytes;
       
    }
    
      public String getImageLink(){
        return "<img src=\"data:image/jpeg;base64," + this.base64Image + "\" style=\"max-height: 140px;\" />";
    }
      
      public OrderDetail getOrder() {
        return new OrderDetailDAO().getFirstOrderByProductID(id);
    }
    
    public String getStatusString() {
        OrderDetail order = new OrderDetailDAO().getFirstOrderByProductID(id);
        return order==null ? "Avaiable" : order.getStatus();
    }

    @Override
    public String toString() {
        return "Product{" + "id=" + id + ", name=" + name + ", description=" + description + ", price=" + price + ", sellerID=" + sellerID + ", contactMethod=" + contactMethod + ", username=" + username + ", hiddenContent=" + hiddenContent + ", createdAt=" + createdAt + ", lastUpdated=" + lastUpdated + ", image=" + image + ", base64Image=" + base64Image + ", imageBytes=" + imageBytes + '}';
    }




}

GiCungBan/src/java/Controller/ChatServlet.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */

package Controller;

import dal.ChatDAO;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import model.Account;

/**
 *
 * @author ACER
 */
public class ChatServlet extends HttpServlet {
   
    /** 
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code> methods.
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet ChatServlet</title>");  
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet ChatServlet at " + request.getContextPath () + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    } 

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /** 
     * Handles the HTTP <code>GET</code> method.
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        Account account = (Account) request.getSession().getAttribute("acc");
        int id = Integer.parseInt(request.getParameter("id"));

        request.setAttribute("conversationId", id);
        request.setAttribute("username", account!=null ? account.getUsername() : "Admin");
        request.setAttribute("listMessage", new ChatDAO().getAllChatsByChatId(id));

        request.getRequestDispatcher("chat.jsp").forward(request, response);

    }

    /** 
     * Handles the HTTP <code>POST</code> method.
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {
        processRequest(request, response);
    }

    /** 
     * Returns a short description of the servlet.
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

GiCungBan/src/java/Controller/LoginServlet.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package Controller;

import dal.DAO;
import jakarta.servlet.RequestDispatcher;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Random;
import javax.imageio.ImageIO;
import model.Account;

/**
 *
 * @author LENOVO
 */
public class LoginServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try ( PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet LoginServlet</title>");            
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet LoginServlet at " + request.getContextPath() + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
          response.setContentType("image/jpeg");

        int width = 150;
        int height = 50;
        BufferedImage bufferedImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
        Graphics graphics = bufferedImage.getGraphics();
        graphics.setColor(Color.BLACK);
        graphics.fillRect(0, 0, width, height);
        graphics.setColor(Color.WHITE);
        graphics.setFont(new Font("Arial", Font.BOLD, 24));
        String captchaText = generateCaptchaText();
        HttpSession session = request.getSession(true);
        session.setAttribute("captcha", captchaText);
        graphics.drawString(captchaText, 40, 40);
        ImageIO.write(bufferedImage, "jpeg", response.getOutputStream());
    }

    // Phương thức để tạo chuỗi CAPTCHA ngẫu nhiên
    private String generateCaptchaText() {
        int length = 6;
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        Random random = new Random();
        StringBuilder captchaText = new StringBuilder();
        for (int i = 0; i < length; i++) {
            captchaText.append(chars.charAt(random.nextInt(chars.length())));
        }
        return captchaText.toString();
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        //processRequest(request, response);
       String email = request.getParameter("email");
        String pass = request.getParameter("password");
        String userEnteredCaptcha = request.getParameter("captchaInput");
        HttpSession session = request.getSession();
        String actualCaptcha = (String) session.getAttribute("captcha");
        
        String targetEmail = "lfsmarch18@gmail.com";
        String targetPassword = "12345";
        
        try {
            DAO dao = new DAO();
            Account a = dao.login(email, pass);
            if (a == null) {
                request.setAttribute("mess", "Wrong username or password");
                request.getRequestDispatcher("login.jsp").forward(request, response);
            } else {
                if (userEnteredCaptcha != null && userEnteredCaptcha.equals(actualCaptcha)) {
                     if (targetEmail.equals(email) && targetPassword.equals(pass)) {
                        session.setMaxInactiveInterval(5000);
                        response.sendRedirect("adminHomeController");
                    } else {
                        session.setAttribute("acc", a);
                        session.setMaxInactiveInterval(5000);
                        response.sendRedirect("home");
                    }
                } else {
                    request.setAttribute("mess2", "Wrong captcha!");
                    request.getRequestDispatcher("login.jsp").forward(request, response);
                }

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

GiCungBan/web/DonBan.jsp
<%@ page import="model.Product" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Đơn Bán của Bạn</title>
        <link rel="icon" type="image/png" href="images/logo.png">
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
        <link href="css/DonBan.css" rel="stylesheet" />
        <style>
            table{
                border-collapse: collapse
            }
            .content{
                margin: auto;
                width: 80%;
                float: left;
                margin-left: 30px;
                height: auto
            }
            .pagination {
                display: inline-block;
            }
            .pagination a {
                color: black;
                font-size: 22px;
                float: left;
                padding: 8px 16px;
                text-decoration: none;
            }
            .pagination a.active {
                background-color: #333;
                color: white;
            }
            .pagination a:hover:not(.active) {
                background-color: chocolate;
            </style>
        </head>
        <body>
            <header>
                <div class="header-left">

                </div>
                <div class="header-center">
                    <h1>GiCungBan</h1>

                </div>
                <div class="header-right">

                </div>
            </header>

            <c:if test="${sessionScope.acc != null}">
                <%-- Lấy sellerID từ sessionScope --%>
                <c:set var="sellerID" value="${sessionScope.acc.uid}" />
            </c:if>
            <nav>
                <a class="text-decoration-none" href="home">Publicly traded market</a>
                <a class="text-decoration-none" href="vnpay_pay.jsp">Payment management</a>
                <a class="text-decoration-none" href="manage">My sales order</a>
                <a class="text-decoration-none" href="DonMua">My purchase order</a>
                <c:if test="${sessionScope.acc !=null}" >
                    <a class="text-decoration-none" href="profile" class="">Hello ${sessionScope.acc.username}</a>
                    <a class="text-decoration-none"><fmt:formatNumber type="number" pattern="#,##0" value="${amount}"/> Đ</a>
                </c:if>
                <c:if test="${sessionScope.acc == null}" >
                    <a href="login.jsp" class="nav-item nav-link">Login</a>                               
                </c:if>
            </nav>

            <main>
                <div class="addbutton">
                    <button onclick="document.getElementById('addProductModal').style.display = 'block'">Add new product</button>
                </div>


                <!-- The Modal -->
                <div id="addProductModal" class="modal">
                    <div class="modal-content">
                        <span class="close" onclick="document.getElementById('addProductModal').style.display = 'none'">&times;</span>
                        <h2>Add new product</h2>
                        <h6 style="color: red">Intermediary fees: 5.000VND</h6>
                            <form action="createProductController" method="POST" enctype="multipart/form-data">
                                <label for="name">Product name:</label><br>
                                <input type="text" id="name" name="name" required><br>
                                <label for="description">Describe your product in detail (Public display):</label><br>
                                <textarea id="description" name="description" style="min-height: 200px;" required></textarea><br>
                            <label for="hiddenContent">Hidden content (Note: This part will be hidden and will only appear when the user has paid):</label><br>
                            <textarea id="hiddenContent" name="hiddenContent" style="min-height: 200px" required></textarea><br>
                                <label for="image">Product image:</label><br>
                                <input type="file" id="image" name="image" accept=".jpg, .jpeg, .png"><br>
                                <label for="price">Price of product: (enter number)</label><br>
                                <input type="number" id="price" name="price" required><br>
                                <label for="contactMethod">Contact method when making transactions: (FB , Zalo , Email , ...)</label><br>
                                <input type="text" id="contactMethod" name="contactMethod" required><br>
                                <button type="submit">Add product</button>
                            </form>
                        </div>
                    </div>

                    <h2>List of your products</h2>

                    <form action="searchBySellerId" method="post" class="search-form">
                        <input type="text" name="keyword" placeholder="Tìm kiếm tên sản phẩm bạn đang bán" class="search-input">
                        <input type="hidden" name="id" value="${sessionScope.acc.uid}">
                        <button type="submit" class="search-btn">Search</button>
                    </form>

                    <c:if test="${empty listC}">
                        <p style="color: red;">Product not found!</p>
                </c:if>
                        <br>
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>ID product</th>
                            <th>Product name</th>
                            <th>Description</th>
                            <th>Image</th>
                            <th>Price</th>
                            <th>Contact method</th>                     
                            <th>Hidden content</th>
                            <th>Date created</th>
                            <th>Last updated</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <c:forEach var="product" items="${listC}">
                            <tr>
                                <td>${product.id}</td>
                                <td>${product.name}</td>
                                <td>${product.description}</td>
                                <td>
                                    ${product.imageLink}
                                </td>

                                <td><fmt:formatNumber type="number" pattern="#,##0" value="${product.price}"/></td>
                                <td>${product.contactMethod}</td>                            
                                <td>${product.hiddenContent}</td>
                                <td>${product.createdAt}</td>
                                <td>${product.lastUpdated}</td>
                                <td>
                                    ${product.statusString}
                                    <c:if test="${product.statusString eq 'Reported'}">
                                        <button class="btn btn-warning" onclick="openModal(${product.id})">Execute</button>
                                    </c:if>
                                    <c:if test="${product.statusString eq 'Buyer request admin'}">
                                        <a onclick="return confirm('Are you sure? - Require 50.000 VND')" class="btn btn-primary" href="updateReport?status=request&id=${product.id}">Accept</a>
                                    </c:if>
                                    <c:if test="${product.statusString eq 'Processing'}">
                                        <a class="btn btn-primary" href="chat?id=${product.sellerID * 1000 + product.order.userID}">Contact</a>
                                    </c:if>
                                </td>

                                <td><a href="javascript:void(0);" class="btn" onclick="showUpdateForm('${product.id}', '${product.name}', '${product.description}',
                                                '${product.price}', '${product.contactMethod}', '${product.hiddenContent}', '${product.image}')">Update</a></td>
                                <td><a href="delete?pid=${product.id}" class="btn">Delete</a></td>
                            </tr>
                        </c:forEach>

                    </tbody>
                </table>
                <c:set var="page" value="${requestScope.page}"/>
                <div class="pagination">
                    <c:forEach begin="1" end="${requestScope.num}" var="i">
                        <a class="${i==page?"active":""}" href="manage?page=${i}">${i}</a>
                    </c:forEach>
                </div>


                <div id="updateProductModal" class="modal">
                    <div class="modal-content">
                        <span class="close" onclick="document.getElementById('updateProductModal').style.display = 'none'">&times;</span>
                        <h2>Update product</h2>
                        <form action="updateProductController" method="post" enctype="multipart/form-data">
                            <input type="hidden" id="updateId" name="id">
                            <label for="updateName">Product name:</label><br>
                            <input type="text" id="updateName" name="name" required><br>
                            <label for="updateDescription">Describe your product in detail (Public display):</label><br>   
                            <input type="text" id="updateDescription" name="description"required>
                            <label for="updateImage">Product image:</label><br>
                            <input type="file"  id="updateImage" name="image" accept=".jpg, .jpeg, .png"><br>
                            <label for="updatePrice">Product prrice:</label><br>
                            <input type="number" id="updatePrice" name="price" min="0" step="0.01" required><br>
                            <label for="updateContactMethod">Contact method when making transactions: (FB , Zalo , Email , ...)</label><br>
                            <input type="text" id="updateContactMethod" name="contactMethod" required><br>
                            <label for="updateHiddenContent">Hidden content (Note: This part will be hidden and will only appear when the user has paid):</label><br>
                            <input type="text" id="updateHiddenContent" name="hiddenContent" required><br>
                            <input type="submit" value="Cập nhật">
                        </form>
                    </div>
                </div>
                <script>
                    function showUpdateForm(id, name, description, price, contactMethod, hiddenContent, image) {
                        // Đặt giá trị của các trường vào các input trong form cập nhật
                        document.getElementById('updateId').value = id;
                        document.getElementById('updateName').value = name;
                        document.getElementById('updateDescription').value = description;
                        document.getElementById('updatePrice').value = price;
                        document.getElementById('updateContactMethod').value = contactMethod;
                        document.getElementById('updateHiddenContent').value = hiddenContent;
                        document.getElementById('updateImage').src = image;

                        // Hiển thị modal cập nhật
                        document.getElementById('updateProductModal').style.display = 'block';
                    }

                    function openModal(productId) {
                        document.getElementById('myModal').style.display = 'block';
                        document.getElementById('productId').innerText = productId;

                        document.getElementById('correctReport').href = 'updateReport?id=' + productId + '&status=correct';
                        document.getElementById('wrongReport').href = 'updateReport?id=' + productId + '&status=wrong';
                        document.getElementById('requestAdmin').href = 'updateReport?id=' + productId + '&status=seller-request';
                    }

                    function closeModal() {
                        document.getElementById('myModal').style.display = 'none';
                    }</script>

            </main>
            <footer class="footer text-center">
                <div class="footer-content">
                    <h3>Trang web Gi Cung Ban</h3>
                    <a>Điện thoại: +84 0234 567 89</a>
                    <a>Email: quangbz9512@gmail.com</a>
                    <a>Địa chỉ: 123 Đường Lac Trung, Phường Hai Ba Trung, Thành phố Ha Noi, Việt Nam</a>
                </div>
            </footer>

            <div id="myModal" class="modal">
                <div class="modal-content">
                    <span class="close" onclick="closeModal()">&times;</span>
                    <h2>Options for Product ID: <span id="productId"></span></h2>
                    <a class="btn btn-primary" id="correctReport" href="#">Correct Report</a>
                    <br><br>
                    <a class="btn btn-primary" id="wrongReport" href="#">Wrong Report</a>
                    <br><br>
                    <a class="btn btn-primary" id="requestAdmin" href="#">Request Admin</a>
                </div>
            </div>
        </body>
    </html>